### ISSUE TITLE
Conditionals and v.077

### ISSUE THREAD

**Issue by guidotripaldi** [grych/drab#116]
It seems that in v. 0.77 Drab changed the way it handles conditionals. If an assign is poked when it is used inside a conditional, Drab rises an error when the state of the condition disables the use of the assign, though if the same assignment is used elsewhere in the same code.

In Drab 0.76 this sample code works as expected:

```elixir
# MyController
...
  render(conn, "index.html", my_list: [])
...
```

```elixir
# MyCommander

defhandler do_update(socket) do
...
   poke(socket, "index.html", my_list: ["A", "B", "C"])
end
```

```eex
<!-- index.html.drab -->

<p> `my_list` is: <%= inspect @my_list %> </p>

<%= if @my_list == [] do %>
	<p> `my_list` is empty</p>
<%= else %>
	<p> <%= inspect @my_list %> </p>
<% end %>
```

but in Drab 0.77, when the above `if` is `true` (i.e. the `@my_list` in `else` isn't displayed), it rises this error :

```
10:22:05.215 [error] Drab Handler failed with the following exception:
** (MatchError) no match of right hand side value: nil
    (drab) lib/drab/live.ex:504: anonymous fn/5 in Drab.Live.do_poke/5
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (drab) lib/drab/live.ex:497: Drab.Live.do_poke/5
    (frontend_web) lib/my_app_web/commanders/my_commander.ex:144: MyAppWeb.MyCommander.do_update/1
    (drab) lib/drab.ex:228: anonymous fn/3 in Drab.handle_callback/3
```

**Comment by grych** [comment]
Again, thanks a million for reporting! You're the best tester ever :)

It is a bug, and I believe it was already fixed. I've tried your code and it works. Could you please try master, or wait for 0.7.8 (coming TONIGHT)?

**Comment by grych** [comment]
Edit. None, it is not fixed yet.

**Comment by guidotripaldi** [comment]
ok, I wait for a your signal to test this again

**Comment by grych** [comment]
Hi @guidotripaldi, please check the master, I believe your issue has been fixed.

**Comment by grych** [comment]
It must be a general bug, as 0.7.8 will introduce the completely redesigned storage for eex engine (no more DETS cache). Did you try `mix clean`?

Also, if you be so kind to share the error and the template which caused it? I will hold the new release until this is fixed.

**Comment by guidotripaldi** [comment]
> Did you try mix clean?
yes, first thing I've done.

I'm trying to generalize the code where the error is announced to better understand the problem, I hope to share everything in a few minutes

**Comment by guidotripaldi** [comment]
It seems that when and `if` condition is encountered, the compiler complains,
this is the minimal code that produce the compilation error:

```eex
# _my_partial.html.drab

<%= if true do  %>
    <p> I'M TRUE </p>
<%= end %>
```

the compiler error is the same ` invalid or duplicate keys for if, only "do" and an optional "else" are permitted` regardless the position or the complexity of the `if` conditional, with or without assignment inside:

```
== Compilation error in file lib/my_app_web/views/test_view.ex ==
** (ArgumentError) invalid or duplicate keys for if, only "do" and an optional "else" are permitted
    (elixir) lib/kernel.ex:2860: Kernel.build_if/2
    (elixir) expanding macro: Kernel.if/2
    lib/my_app_web/templates/test/partials/_my_partial.html.drab:31: MyAppWeb.testView."partials/_my_partial.html"/1
    (phoenix) /my/app/dir/my_app/apps/my_app_web/lib/my_app_web/views/test_view.ex:1: Phoenix.Template.__before_compile__/1
```

**Comment by guidotripaldi** [comment]
I was hasty, this is not the right error condition. The code is complex and the html is composed of many partials, I'm trying to investigate better

**Comment by guidotripaldi** [comment]
new test, it seems that the compiler is sensible to this code configuration, i.e. when a second `if` testing an assignment, enclosed in HTML, is present after the first `if`/`else`:
```eex
<%= 
  result =
    if true do
      "I'M TRUE"
    else
      "I'M FALSE"
    end
%>	

 <div>
    <%= 
      if @user.id != "xyz" do
        "I'M TRUE"
      end
    %>
</div>
```

Same error near the first `if`, `invalid or duplicate keys for if, only "do" and an optional "else" are permitted`

**Comment by grych** [comment]
Yes, I've got it! Thanks

**Comment by grych** [comment]
Hi @guidotripaldi, I believe I've found where the issue was. Could you please get the current master and check again?

**Comment by guidotripaldi** [comment]
Yess, now it works! great!

**Comment by grych** [comment]
Please close if you confirm it's solved with master

**Comment by guidotripaldi** [comment]
issue solved.

**Comment by guidotripaldi** [comment]
I'm sorry to reopen the case but I discovered another similar case that breaks the compiler, Drabs doesn't like nested `if` when they are followed by HTML:

```eex
  <%= 
    result =
      if @test1 == "a" do
        "A"
      else
        if @test1 == "b" do
          "B"
        else
           if @test1 == "c" do
             "C"
           end
         end
      end
  %>	

  <div>
    <%= 
       if @test1 != "d" do
         "D"
       else
         "E"
       end
    %>
  <div>
```

```
== Compilation error in file lib/my_app_web/views/test_view.ex ==
** (ArgumentError) expected var! context to expand to an atom, got: {:other, []}
    (elixir) expanding macro: Kernel.var!/2
    lib/my_app_web/templates/test/drabtest1.html.drab:12: MyAppWeb.TestView."drabtest1.html"/1
    (elixir) expanding macro: Kernel.if/2
    lib/my_app_web/templates/test/drabtest1.html.drab:9: MyAppWeb.TestView."drabtest1.html"/1
    (phoenix) /path/to/my/app/myapp/apps/my_app_web/lib/my_app_web/views/test_view.ex:1: Phoenix.Template.__before_compile__/1
```

**Comment by grych** [comment]
Thanks a lot! I think I know which part of the engine causes those troubles, and I will try to debug it over the weekend

**Comment by guidotripaldi** [comment]
I don't know if I can help you to debug the code, but if you need help just ask

**Comment by grych** [comment]
Thanks! I really appreciate your ability to find the issues :) Keep it going and we will reach the goal (1.0) shortly!

I will describe what probably causes this issue (and caused few previous): Phoenix compiles the template to the nested list of iodata and quoted expressions. So when you have a templates like `<div><%= function(x) %></div>`, it will be compiled to something like `["<div>", {:function, [], [{:x, [], Elixir}]}, "</div>"]`. Drab's eex engine produces the same at the end, as we want to keep all great Phoenix functionality up and running.

Drab.Live is for updating assigns, but how does it know where the assigns are? It is collecting this data during the compilation of the template. When it reaches the expression (`function(x)` in the last template), it collects the assigns used in the expression. But even more important of having the assign name is to mark where is the expression with the assigns. Drab does it injecting the own attribute, `drab-ampere`, with the unique value of some hash, to the **last not closed tag**.

If there is no not closed tag available, Drab surrounds the expression with `<span drab-ampere="xxx">`.

In this small example it is easy. The last tag is `<div>`, so we replace it with `<div drab-ampere='xxx'>`. But the real templates are hierarchical, having nested expression, so Drab must recursively search for the last opened tag. For example, the issue with html comments came because I forgot they exists and treated them as a normal tags. They had attribute `drab-ampere` after processing by Drab's engine :)

Searching and injecting the drab-ampere attribute is the most job of the module `Drab.Live.HTML`. First, the compiled template part is tokenized, to the list with something like `{:tag, "div"}` + quoted expressions, then it searches this from the end, injects attribute to the found, last opened tag, reverse the list and de-tokenize it. At the end we have iodata + expressions list, only with injected attribute. It is really complicated when it goes to the practice. And it is causing the bugs.

So I think I might over-complicate this algorithm, and it might be more straight way to get the result. In this case, it would be easier with the language having mutable data :-)

**Comment by guidotripaldi** [comment]
I've distilled better the case. The error manifests exactly when all these conditions are concurrently present:

- there is a nested `if`; # _no matter if it contains or not some assigns_
- it is followed, somewhere, by an assign; # _no need to be stuck together_
- the assign is preceded, somewhere, by any opening HTML tag; # _no need to be stuck together

This is the minimal code that exemplifies these conditions:
```
<%= 
    if true do
      if true do
        true
      end
    else
      false
    end
%>	

<!-- anything else in the middle -->

<div>
  <!-- anything else in the middle -->
  <%= inspect @test1 %>

```

**Comment by grych** [comment]
So the issue must be when processing nested expressions (between do and end). Thanks!

I need to rethink the process of injecting the attribute. It must be an easier way to archive this.

**Comment by guidotripaldi** [comment]
nested means recursion, maybe something related to the accumulator

**Comment by guidotripaldi** [comment]
Not just nested `if`. This is another case, where inside the `if` you set a variable, followed, as usual, by the opening tag and the use of the assign:

```eex
<%= 
  if true do
    some_value = 42
  end
%>	

<div>
  <%= 
    inspect @test
  %>
</div>
```

**Comment by grych** [comment]
Nice catch, thx!

**Comment by grych** [comment]
Hi @guidotripaldi,
I refactored a major part of the engine. I believe your issues are now solved! All your examples are compiling without an issue now.

Please check the master.

**Comment by guidotripaldi** [comment]
Thank you Tomek! I'll test the new version ASAP

**Comment by guidotripaldi** [comment]
Yes! Now it compiles and works correctly :)
