### ISSUE TITLE
Safari troubles

### ISSUE THREAD

**Issue by taorg** [grych/drab#13]
Hello, we think we've found a bug.
We have a regular phoenix project and we configured Drab, to minimize JS, everything works fine as long as you try with Chrome or Firefox, but Safari emits two errors whenever you change from one page to another (http://localhost:4000/users >> http://localhost:4000/users/1/edit)
```
1º WebSocket connection to 'ws://localhost:4000/phoenix/live_reload/socket/websocket?vsn=1.0.0' failed: WebSocket is closed due to suspension.
2º WebSocket connection to 'ws://localhost:4000/socket/websocket?__drab_return=SFMyNTY.g3QAAAACZAAEZGF0YWwAAAADaAJkAAxfX2NvbnRyb2xsZXJkACJFbGl4aXIuUGhhbnRhd2ViLkFBLlVzZXJDb250cm9sbGVyaAJkAAhfX2FjdGlvbmQABWluZGV4aAJkAAlfX2Fzc2lnbnNqamQABnNpZ25lZG4GADU68h9bAQ.KdcBNzKYoJw-qOXZpFp24hwh0LHuMtM6mb1X9TuxTJo&vsn=1.0.0' failed: WebSocket is closed due to suspension.
```
It doesn't if you just reload page.
This happens in both iOS & OSX, but iOS is critical, because Safari crashes on our old iPAD, you just navigate between pages with some simple commanders and it crashes.

We haven't investigate more, we try to help you, because this seems a critical one, at least for us.

Greetings

**Comment by taorg** [comment]
With Safari Console enable just change from https://tg.pl/drab to https://tg.pl/drab/docs#drab and you'll get

`WebSocket connection to 'wss://tg.pl/drab/socket/websocket?__drab_return=SFMyNTY.g3QAAAACZAAEZGF0YWwAAAADaAJkAAxfX2NvbnRyb2xsZXJkAB1FbGl4aXIuRHJhYlBvYy5QYWdlQ29udHJvbGxlcmgCZAAIX19hY3Rpb25kAAVpbmRleGgCZAAJX19hc3NpZ25zbAAAAAJoAmQAB3VzZXJfaWRhBGgCZAAJYW55X290aGVybQAAAAR0ZXN0ampkAAZzaWduZWRuBgBPIwcgWwE.aWFZb6pUdohLzZ0BQzTFe9ZoAzzNDn3w3y5xDAPBKJo&vsn=1.0.0' failed: WebSocket is closed due to suspension.`

**Comment by grych** [comment]
I can't reproduce this error on my Safaris.

What is the version of Safari you are using? Is it going through a proxy or direct?

**Comment by taorg** [comment]
Umm this is weird.
On Mac Os Sierra 10.12.3 (16D32) Safari Version 10.0.3 (12602.4.8)
On iOs version is 9.3.5 (same excepcion and always crashes)  

I can record a video or take some screenshots to show you what happen.
I got another Mac I'll test it later and give you feed back.

Thnx

**Comment by grych** [comment]
The issue is not only the Drab problem, as you have the same message in `live_reload` socket - it is a general websocket problem (Drab uses standard Phoenix sockets). Anyway we need to debug it somehow.

I have exactly the same versions of Safari on Sierra. I've also check on iPhone and iPad simulators, no issue.

Are you connection through any proxy? Transparent proxy? 3G provider? But it would be strange, as you have the same issue while connecting to localhost.

**Comment by taorg** [comment]
Yes, I do agree with you, it seems something more general and we have somehow to work it out .
Because first step to solve a problem is to reproduce it, I've recorded a [video](http://ns206337.ovh.net/screencast%202017-04-02%2013-26-15.mp4) to show you the error just with your demo website.
Be sure you've activated Safari's console feature ["Keep Log on Navigation"](http://ns206337.ovh.net/SafariConsoleActivation.png) because the when you have it [deactivated](http://ns206337.ovh.net/SafariConsoleDeactivation.png) the error just appears for a second and just disappears in a blink.

I've also test it with another Mac OS (Yosemite) and found same excepction.
Hope this could help you.

**Comment by grych** [comment]
Thanks a lot,
I can see it now (after enabling "keep log on navigation"), and I don't think it is an issue! When you navigate away from the page, it breaks the websocket connection. And it supposed to be like that - on the server side, Drab GenServer dies as well.

Please notice that event with this message, all websocket functionality works correctly on Safari. Isn't it?

I replicated the same behaviour on pure, new phoenix project (`mix phoenix.new test --no-ecto`), and have the same message (`[Error] WebSocket connection to 'ws://localhost:4000/phoenix/live_reload/socket/websocket?vsn=1.0.0' failed: WebSocket is closed due to suspension.`) when navigating away. So if you still find is as a bug, please report it to the phoenix project team.

**Comment by taorg** [comment]
Great, 
Yes I'm going to report it to Phoenix team, because on iOS it crashes Safari, and also it doesn`t seem right way to manage websockets when you navigate from one page to another.

**Comment by OvermindDL1** [comment]
Uh, Safari crashing when using websockets would in no possible way be a server (phoenix) issue at all, that would purely be a browser issue...

**Comment by taorg** [comment]
Yes, annoying error indeed but yes.
It's not exactly when you use websockets, but when it closes because you navigate from one page to another.
