### ISSUE TITLE
Allow to define a Layout commander or Shared Commander

### ISSUE THREAD

**Issue by JanStevens** [grych/drab#59]
I have a button in my navbar that is displayed on every page, When pressing this button I change the state and display of it using Drab.

The problem is that I can only define one commander for every controller, meaning that all my controllers will use the same drab commander. I would like to specify the `SharedCommander` or `LayoutCommander` that is available on every page that is rendered for a specific layout.

This way my controllers can have separate commanders while I retain my general functionality

**Comment by grych** [comment]
Hi @JanStevens,
This is in plans for the future, you'll be able to specify the commander name directly in the html template with `drab-commander` attribute.
Stay tuned.

**Comment by grych** [comment]
You may now use the full path to the event handler function:

    <button drab-click='MyAppWeb.MyCommander.button_clicked'>clickme</button>

Notice that `MyAppWeb.MyCommander` **must be a Drab commander**. For security reasons, we don't want to allow users to run any Elixir function :-)

**Comment by grych** [comment]
Reopening because of the security concerns mentioned https://github.com/grych/drab/commit/b66852c4bd7aaf2be35b59c30b1488b578d04d8b#commitcomment-25212937

**Comment by grych** [comment]
The plan to tighten the security:
  
* [ ] the ordinary commander accepts only requests coming from the page generated with the corresponding controller
* [ ] the ability to run elixir functions/2 in commanders must be mentioned in every corner of documentation
* [ ] the shared commander accepts requests from any page
* [ ] all handlers in shared commander must be whitelisted
* [ ] `before_handler` in shared commander gets a context (controller name) of the page launched the event

**Comment by OvermindDL1** [comment]
All around Yay!  ^.^

An idea I just got, you could 'expose' a function publically (without needing a Shared commander or so) like:

```elixir
  defpublic check_status(socket, dom_sender) do
    # return false or nil to prevent event handler to be launched
  end
```

So use `defpublic` instead of `def`, which should generate code like:

```elixir
  def check_status(socket, dom_sender) do
    # return false or nil to prevent event handler to be launched
  end
  def unquote(:"$PUBLIC$check_status")(socket, dom_sender), do: check_status(socket, dom_sender)
```

And make it so the templates can only call a shared/public function by testing if the above `:"$PUBLIC$..."` form of it exists and calling it instead (this also allows a user to override the public version if they want, like to add more security or so).

**Comment by grych** [comment]
Public handlers must be whitelisted now.

```elixir
defmodule MyApp.MyCommander
  use Drab.Commander
  public [:handler1, :handler2]

  def handler1(socket, sender) do
    ...
  end
end
```

You can only use dot notation `MyApp.MyCommander.my_handler` in the browser only for public handlers. 

New functions: `controller/1` and `action/1` to retrieve the controller and action in order to check security. May be used in handler or in a callbacks.

"Normal" handlers remains the same, so they don't have to be whitelisted. Updated the documentation to make it clear, that all the functions with arity of 2 must be considered as handlers.
