### ISSUE TITLE
Share socket

### ISSUE THREAD

**Issue by OvermindDL1** [grych/drab#8]
Any chance on making it capable of sharing an existing socket by adding a drab channel handler to it and passing some javascript code to the `Drab.Client.js` call that can access the existing socket?  Duplicate websockets are killed by certain corporate network setups.  :-)

**Comment by grych** [comment]
JS side is simple, there is a global object `Drab`, I will add socket as a property. 

    var channel = Drab.socket.channel("mychannel:whatever", {})
    channel.join()

What concerns me is how to define additional channels in your application. Now you run the socket behind the scene, by using `Drab.Endpoint`. We need to define an API to tell Drab to create additional channels. It might look like:

      use Drab.Endpoint, channels: ["mychannel:whatever", DrabPoc.Socket]

where `DrabPoc.Socket` is a module in your Phoenix application.

Or even like below, to be more consistent with Plug:

    use Drab.Endpoint
    drab Drab.AddChannel, "mychannel:whatever", DrabPoc.Socket

**Comment by OvermindDL1** [comment]
I'd just have the user add a single "drab:*" channel, then you can internally dispatch inside of it as it will get all channel requests that start with "drab:", nicely compartmentalized.  :-)

**Comment by grych** [comment]
I redesigned the way how Drab injects its code to your App. Now, it is done in the `MyApp.UserSocket` instead of `MyApp.Endpoint`:

```
defmodule MyApp.UserSocket do
  use Phoenix.Socket
  use Drab.Socket

  channel "mychannel:*", MyApp.Channel
  # and so on...
end
```

Please notice that by default Drab tries to use default "/socket" path, in case you want to use a different one, you need to specify it in the config:

```
config :drab, 
  socket: "/drab/socket"
```

On the client side, there is a global object `Drab` and you can use its socket: `Drab.socket`.

This change is included in b3b2d8ce24480501a6104c777e85c0190aeefc82, and will be a part of release `v0.3.0`, coming soon.

**Comment by OvermindDL1** [comment]
Awesome!  This also means I can use my custom token authentication that I use on my main socket.  :-)

**Comment by OvermindDL1** [comment]
Which reminds me, I either need to create the socket on my side, or I need to set up yours a special way before you connect and set up certain parameters, where is that documented?  :-)

**Comment by grych** [comment]
Yes, now you need to create a socket on your side (notice it is done by default in endpoint.ex and user_socket.ex). 
Whenever you want to use a path different than "/socket", you need to configure this.

Updated documentation is coming with v0.3.0 in a couple of days ;)

**Comment by grych** [comment]
Drab always starts on the browser side on page load, it connects and it is passing some Token with internal information (from which controller and action is was rendered).

This is why you probably can't use your own authentication, if it rely on `connect` callback in the `UserSocket`. Your `connect` callback will never be launched, because Drab intercepts it first. (It is confusing and must be changed or very well documented before releasing v0.3.0)

However, there are 2 ways to accomplish the authentication:
* first at all, Drab Commander can have an access to the Plug Session, so if you store something like "userid" there, you are saved
* additionally, you can pass your own parameters to the Drab.Client when injecting Drab JS:

    <%= Drab.Client.js(@conn, user_id: 4, name: "Zdzisław") %>

this will add the additional fields to the Drab Token, and after connect they will just appear in assigns:

    %Phoenix.Socket{assigns: %{
          __action: :index, __controller: DrabPoc.PageController, 
          __drab_pid: #PID<0.1430.0>, __url_path: "/drab", 
          name: "Zdzisław", user_id: 4}, ...}

**Comment by grych** [comment]
Changes released in https://github.com/grych/drab/releases/tag/v0.3.0
